[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[nixpacks]
nixPackages = ["python312", "gcc"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
SERVICE_NAME = "comms-api"
LOG_LEVEL = "info"
CORS_ORIGINS = "*"
WEBSOCKET_PING_INTERVAL = "30"
WEBSOCKET_PING_TIMEOUT = "120"

[service]
name = "comms-api"
internalPort = 8000
auto_deploy = true
websocket = true

[mounts]
source = "comms_api_data"
destination = "/data"
