# This is an intentionally empty railway.toml file
# 
# Railway was caching a previous version of this file that contained:
#   uvicorn app.main:app --host 0.0.0.0 --port $PORT
#
# This caused deployment failures because $PORT wasn't being expanded.
# 
# This empty file overrides that cached version and forces Railway
# to use the Dockerfile's ENTRYPOINT instead, which properly handles
# the PORT environment variable through a Python script.
#
# DO NOT ADD ANY COMMANDS HERE - let the Dockerfile handle everything.
