[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[nixpacks]
nixPackages = ["python312", "gcc"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
SERVICE_NAME = "internal-api"
LOG_LEVEL = "info"
CORS_ORIGINS = "*"

[service]
name = "internal-api"
internal_port = 8000
auto_deploy = true

[mounts]
source = "internal_api_data"
destination = "/data"
